#!/usr/bin/env bash

packages=(
    "fd"
    "go"
    "git"
    "gcc"
    "npm"
    "make"
    "gimp"
    "btop"
    "teams"
    "godot"
    "which"
    "rider"
    "zellij"
    "nodejs"
    "python3"
    "ripgrep"
    "discord"
    "shotcut"
    "firefox"
    "unityhub"
    "luarocks"
    "brave-bin"
    "libnotify"
    "dotnet-sdk"
    "obs-studio"
    "webcord-bin"
    "thunderbird"
    "qt5-wayland"
    "sfxr-qt-bin"
    "wl-clipboard"
    "drawio-desktop"
    "tor-browser-bin"
    "tree-sitter-cli"
    "libreoffice-fresh"
    "neovim-nightly-bin"
)

exported_apps=(
    "obs"
    "gimp"
    "btop"
    "brave"
    "teams"
    "godot"
    "rider"
    "discord"
    "shotcut"
    "firefox"
    "neovide"
    "unityhub"
    "thunderbird"
    "webcord"
    "pwvucontrol"
    "sfxr-qt"
    "drawio"
    "tor-browser"
    "libreoffice"
)

paru -S --needed --noconfirm "${packages[@]}"
paru -S --needed --noconfirm neovide --assume-installed neovim
paru -S --needed --noconfirm pwvucontrol --overwrite "/usr/lib/libgstcuda-1.0.so*"
mkdir -p "$HOME/.local/share/unity3d"
for app in "${exported_apps[@]}"; do
    distrobox-export --app "$app"
done
