set -g base-index 1
setw -g pane-base-index 1

set -g clock-mode-style 24

set -g status-keys vi
setw -g mode-keys vi

set -g mouse off

bind -N "Select pane to the left of the active pane" h select-pane -L
bind -N "Select pane below the active pane" j select-pane -D
bind -N "Select pane above the active pane" k select-pane -U
bind -N "Select pane to the right of the active pane" l select-pane -R

bind -r -N "Resize the pane left by 5" H resize-pane -L 5
bind -r -N "Resize the pane down by 5" J resize-pane -D 5
bind -r -N "Resize the pane up by 5" K resize-pane -U 5
bind -r -N "Resize the pane right by 5" L resize-pane -R 5

set -g default-terminal "screen-256color"

set -s escape-time 10

set-option -g focus-events on
bind -N "Create a new session" C-c new-session
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'catppuccin/tmux'

set -g @resurrect-processes '"~nvim->nvim" lazydocker'
set -g @resurrect-strategy-nvim 'session'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run '~/.tmux/plugins/tpm/tpm'
