$HYPRPAPER_BG_FALLBACK=/run/host/usr/share/hypr/wall2.png
$HYPRPAPER_BG=$DISTROBOX_HOST_HOME/Pictures/Wallpapers/Snow-valley.jpg

ipc = on
preload = $HYPRPAPER_BG_FALLBACK
wallpaper = ,$HYPRPAPER_BG_FALLBACK
preload = $HYPRPAPER_BG
wallpaper = ,$HYPRPAPER_BG
