[trantbox-games]
home=$HOME/distrobox-home/trantbox-games
image=ghcr.io/ublue-os/bazzite-arch:latest
entry=true
nvidia=true
replace=true
start_now=true
additional_packages=steam umu-launcher
additional_flags=--env ZDOTDIR=$HOME
exported_apps=steam

; volume=/extra/$USER/.local/share/Steam:$HOME/distrobox-home/trantbox-games/.local/share/Steam
# The line before this would error because I intend to comment it like that
# since that it is a volume for my specific computer so just add '#' before the ';'

[trantbox-desktop]
home=$HOME/distrobox-home/trantbox-desktop
image=ghcr.io/ublue-os/bazzite-arch:latest
entry=true
nvidia=true
replace=true
start_now=true
additional_packages=noto-fonts-emoji
additional_packages=firefox helvum obs-studio webcord nvidia-settings
additional_packages=btop
additional_flags=--env ZDOTDIR=$HOME
init_hooks=sudo -u $USER -- paru -S --noconfirm teams pwvucontrol bottles
init_hooks=sudo -u $USER -- paru -S --noconfirm hyprsysteminfo
exported_apps=firefox helvum obs webcord nvidia-settings
exported_apps=btop
exported_apps=teams pwvucontrol bottles hyprsysteminfo
volume=$HOME/.mozilla:$HOME/distrobox-home/trantbox-desktop/.mozilla

[trantbox-services]
home=$HOME/distrobox-home/trantbox-services
image=archlinux:latest
entry=true
replace=true
start_now=true
additional_packages=ttf-firacode-nerd noto-fonts-emoji noto-fonts-cjk
additional_packages=hyprpaper fcitx5 fcitx5-configtool fcitx5-unikey waybar brightnessctl playerctl
additional_packages=swaync profile-sync-daemon
additional_packages=hyprpicker hyprshot cliphist wl-clipboard wtype
additional_flags=--env HYPRSHOT_DIR=$HOME/Pictures
additional_flags=--env ZDOTDIR=$HOME
exported_apps=fcitx5-configtool
exported_bins=/usr/bin/wl-copy /usr/bin/wl-paste /usr/bin/wtype
exported_bins=/usr/bin/hyprpicker /usr/bin/hyprshot /usr/bin/hyprshot /usr/bin/cliphist
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/hyprctl
volume=$HOME/.mozilla:$HOME/distrobox-home/trantbox-services/.mozilla

[trantbox-dev]
home=$HOME/distrobox-home/trantbox-dev
image=archlinux:latest
entry=true
replace=true
start_now=true
additional_packages=git gcc make which fzf ripgrep fd nodejs npm neovim neovide tmux dysk
additional_packages=stow fastfetch zoxide python3 tree-sitter-cli dotnet-host additional_flags=--env ZDOTDIR=$HOME
exported_apps=neovide
exported_bins=/usr/bin/nvim /usr/bin/tmux /usr/bin/dysk /usr/bin/fzf
exported_bins=/usr/bin/stow /usr/bin/fastfetch /usr/bin/zoxide
volume=$HOME/.ssh:$HOME/distrobox-home/trantbox-dev/.ssh
volume=$HOME/.config/git:$HOME/distrobox-home/trantbox-dev/.config/git
