[trantbox-desktop]
home=$DISTROBOX_HOME/trantbox-desktop
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
nvidia=true
start_now=true

# dependencies
additional_packages=libnotify wl-clipboard qt5-wayland
# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-desktop/.config/fish:ro
# main
additional_packages=firefox helvum obs-studio nvidia-settings btop gimp shotcut discord libreoffice-fresh drawio-desktop
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm webcord-bin brave-bin tor-browser-bin teams
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm pwvucontrol hyprsysteminfo-git bottles sfxr-qt-bin
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/hyprctl
exported_apps=firefox helvum obs nvidia-settings btop gimp shotcut discord libreoffice drawio
exported_apps=webcord brave tor-browser teams pwvucontrol hyprsysteminfo bottles sfxr
volume=$DOTFILES_DIR/trantbox/trantbox-desktop/dot-config/WebCord/Themes:$DISTROBOX_HOME/trantbox-desktop/.config/WebCord/Themes:ro
volume=$DOTFILES_DIR/trantbox/trantbox-desktop/dot-config/btop:$DISTROBOX_HOME/trantbox-desktop/.config/btop:ro

init_hooks=touch /etc/init

[trantbox-games]
home=$DISTROBOX_HOME/trantbox-games
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
nvidia=true
start_now=true

# essential
additional_packages=openal pipewire pipewire-pulse pipewire-alsa pipewire-jack wireplumber mangohud
additional_flags=--env __NV_PRIME_RENDER_OFFLOAD=1
additional_flags=--env __GLX_VENDOR_LIBRARY_NAME=nvidia
additional_flags=--env __VK_LAYER_NV_optimus=NVIDIA_only
additional_flags=--env __GL_THREADED_OPTIMIZATIONS=0
# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-games/.config/fish:ro
;    volume=/extra/$USER/.local/share/Steam:$DISTROBOX_HOME/trantbox-games/.local/share/Steam:rw
;    volume=/extra/$USER/Games:$DISTROBOX_HOME/trantbox-games/Games:rw
# main
additional_packages=steam umu-launcher
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm legacy-launcher
exported_apps=steam legacy-launcher
volume=$DOTFILES_DIR/trantbox/trantbox-games/dot-local/share/Steam/steam_dev.cfg:$DISTROBOX_HOME/trantbox-games/.local/share/Steam/steam_dev.cfg:ro

init_hooks=touch /etc/init

[trantbox-dev]
home=$DISTROBOX_HOME/trantbox-dev
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
nvidia=true
start_now=true

# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-dev/.config/fish:ro
#    volume=/extra/$USER/Unity:$DISTROBOX_HOME/trantbox-dev/Unity:rw
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/stow
# essential
additional_packages=wl-clipboard ripgrep gcc make which git fzf nodejs npm
additional_packages=python3 tree-sitter-cli dotnet-sdk luarocks
exported_bins=/usr/bin/rg /usr/bin/fzf
# general
additional_packages=neovim neovide zellij
exported_apps=neovide
exported_bins=/usr/bin/nvim /usr/bin/zellij
volume=$DOTFILES_DIR/trantbox/trantbox-dev/dot-config/nvim:$DISTROBOX_HOME/trantbox-dev/.config/nvim:rw
volume=$DOTFILES_DIR/trantbox/trantbox-dev/dot-config/zellij:$DISTROBOX_HOME/trantbox-dev/.config/zellij:rw
volume=$HOME/.ssh:$DISTROBOX_HOME/trantbox-dev/.ssh:ro
volume=$HOME/.config/git:$DISTROBOX_HOME/trantbox-dev/.config/git:ro
# gamedev
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm godot-beta-bin unityhub rider
init_hooks=[ -d $DISTROBOX_HOME/trantbox-dev/.local/share/unity3d ] || mkdir -p $DISTROBOX_HOME/trantbox-dev/.local/share/unity3d
exported_apps=godot-beta unityhub rider
volume=$DOTFILES_DIR/trantbox/trantbox-dev/dot-local/share/unity3d/.gitkeep:$DISTROBOX_HOME/trantbox-dev/.local/share/unity3d/.gitkeep

init_hooks=touch /etc/init

[trantbox-services]
home=$DISTROBOX_HOME/trantbox-services
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
start_now=true

# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-services/.config/fish:ro
volume=$DOTFILES_DIR/trant/Pictures/Wallpapers:$DISTROBOX_HOME/trantbox-services/Pictures/Wallpapers:ro
# general
additional_packages=fcitx5 fcitx5-unikey fcitx5-configtool playerctl
exported_apps=fcitx5-configtool
exported_bins=/usr/bin/fcitx5 /usr/bin/playerctld /usr/bin/playerctl /usr/bin/eww
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm eww
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-local/share/fcitx5/themes:$DISTROBOX_HOME/trantbox-services/.local/share/fcitx5/themes:ro
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/fcitx5:$DISTROBOX_HOME/trantbox-services/.config/fcitx5:rw
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/waybar:$DISTROBOX_HOME/trantbox-services/.config/waybar:ro
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/eww:$DISTROBOX_HOME/trantbox-services/.config/eww:ro
# wayland
additional_packages=swaync waybar cliphist wl-clipboard
exported_bins=/usr/bin/wl-copy /usr/bin/wl-paste /usr/bin/cliphist
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/swaync:$DISTROBOX_HOME/trantbox-services/.config/swaync:ro
# hyprland
additional_packages=hyprpaper hyprsunset
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/hypr:$DISTROBOX_HOME/trantbox-services/.config/hypr:ro
# X11
additional_packages=picom feh
exported_bins=/usr/bin/picom /usr/bin/feh
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/picom:$DISTROBOX_HOME/trantbox-services/.config/picom:ro

init_hooks=touch /etc/init

[trantbox-utils]
home=$DISTROBOX_HOME/trantbox-utils
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
start_now=true

# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-utils/.config/fish:ro
# essential
additional_packages=fd fastfetch zoxide catimg unzip bat libnotify unrar trash-cli
exported_bins=/usr/bin/fd /usr/bin/fastfetch /usr/bin/zoxide
exported_bins=/usr/bin/catimg /usr/bin/unzip /usr/bin/notify-send /usr/bin/unrar /usr/bin/wtype /usr/bin/bat
exported_bins=/usr/bin/trash-empty /usr/bin/trash-list /usr/bin/trash-put /usr/bin/trash-restore /usr/bin/trash-rm
volume=$DOTFILES_DIR/trantbox/trantbox-utils/dot-config/fastfetch:$DISTROBOX_HOME/trantbox-utils/.config/fastfetch:ro
# wayland
additional_packages=wtype
# hyprland
additional_packages=hyprshot hyprpicker
exported_bins=/usr/bin/hyprshot /usr/bin/hyprpicker
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/hyprctl
