[trantbox-games]
home=$HOME/.local/share/distrobox/home/trantbox-games
image=ghcr.io/ublue-os/bazzite-arch:latest
entry=true
nvidia=true
replace=true
start_now=true
additional_packages=steam umu-launcher
init_hooks=pacman -Q legacy-launcher || sudo -u $USER -- paru -S --noconfirm --needed legacy-launcher
exported_apps=steam legacy-launcher

; volume=/extra/$USER/.local/share/Steam:$HOME/.local/share/distrobox/home/trantbox-games/.local/share/Steam:rw
# The line before this would error because I intend to comment it like that
# since that it is a volume for my specific computer so just add '#' before the ';'

[trantbox-desktop]
home=$HOME/.local/share/distrobox/home/trantbox-desktop
image=archlinux:latest
entry=true
nvidia=true
replace=true
start_now=true
additional_packages=firefox helvum obs-studio nvidia-settings btop fcitx5-configtool
additional_packages=qt6ct
additional_packages=base-devel
init_hooks=pacman -Q paru-bin                                           || sudo -u $USER -- makepkg --noconfirm --needed -si -D $HOME/paru-bin
init_hooks=pacman -Q webcord-bin teams brave-bin pwvucontrol bottles    || sudo -u $USER -- paru -S --noconfirm --needed webcord-bin teams brave-bin pwvucontrol bottles
init_hooks=pacman -Q godot-beta-bin unityhub                            || sudo -u $USER -- paru -S --noconfirm --needed godot-beta-bin unityhub
init_hooks=pacman -Q hyprsysteminfo-git hyprqt6engine-git               || sudo -u $USER -- paru -S --noconfirm --needed hyprsysteminfo-git hyprqt6engine-git
init_hooks=pacman -Q tor-browser-bin                                    || sudo -u $USER -- paru -S --noconfirm --needed tor-browser-bin
exported_apps=firefox helvum obs nvidia-settings btop fcitx5-configtool
exported_apps=qt6ct
exported_apps=webcord brave tor-browser teams pwvucontrol bottles godot-beta unityhub hyprsysteminfo

[trantbox-services]
home=$HOME/.local/share/distrobox/home/trantbox-services
image=archlinux:latest
entry=true
replace=true
start_now=true
additional_packages=fcitx5 fcitx5-unikey waybar playerctl picom
additional_packages=swaync profile-sync-daemon cliphist wl-clipboard wtype libnotify
additional_packages=hyprpaper hyprpicker
additional_packages=base-devel
init_hooks=pacman -Q paru-bin || sudo -u $USER -- makepkg --noconfirm --needed -si -D $HOME/paru-bin
init_hooks=cp /usr/share/psd/contrib/brave /usr/share/psd/browsers/brave
exported_bins=/usr/bin/fcitx5 /usr/bin/playerctld /usr/bin/picom
exported_bins=/usr/bin/wl-copy /usr/bin/wl-paste /usr/bin/wtype /usr/bin/notify-send
exported_bins=/usr/bin/hyprpicker /usr/bin/cliphist
volume=$HOME/.local/share/distrobox/home/trantbox-desktop/.mozilla:$HOME/.local/share/distrobox/home/trantbox-services/.mozilla:rw
volume=$HOME/.local/share/distrobox/home/trantbox-desktop/.config/BraveSoftware:$HOME/.local/share/distrobox/home/trantbox-services/.config/BraveSoftware:rw

[trantbox-dev]
home=$HOME/.local/share/distrobox/home/trantbox-dev
image=archlinux:latest
entry=true
replace=true
start_now=true
additional_packages=gcc make which git fzf nodejs npm neovim neovide tmux
additional_packages=python3 tree-sitter-cli dotnet-host
exported_apps=neovide
exported_bins=/usr/bin/nvim /usr/bin/tmux /usr/bin/fzf
volume=$HOME/.ssh:$HOME/.local/share/distrobox/home/trantbox-dev/.ssh:rw
volume=$HOME/.config/git:$HOME/.local/share/distrobox/home/trantbox-dev/.config/git:rw

[trantbox-utils]
home=$HOME/.local/share/distrobox/home/trantbox-utils
image=archlinux:latest
entry=true
replace=true
start_now=true
additional_packages=ripgrep fd dysk stow fastfetch zoxide brightnessctl catimg
additional_packages=base-devel
init_hooks=pacman -Q paru-bin   || sudo -u $USER -- makepkg --noconfirm --needed -si -D $HOME/paru-bin
init_hooks=pacman -Q hyprcap    || sudo -u $USER -- paru -S --noconfirm --needed hyprcap
exported_bins=/usr/bin/rg /usr/bin/fd /usr/bin/dysk /usr/bin/stow /usr/bin/fastfetch
exported_bins=/usr/bin/zoxide /usr/bin/catimg /usr/bin/hyprcap
