# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

exec --no-startup-id blueman-applet

exec --no-startup-id fcitx5 -d
exec --no-startup-id feh --bg-fill $HOME/Pictures/Wallpapers/Snow-valley.jpg
exec --no-startup-id playerctld
exec --no-startup-id picom
