[Unit]
Wants=waybar.service swayidle.service hyprpolkitagent.service fumon.service
Wants=trantbox-services-awww.service trantbox-services-wlsunset.service
Wants=trantbox-services-swaync.service trantbox-services-cliphist.service
