[Unit]
Wants=distrobox-container@trantbox-desktop.service distrobox-container@trantbox-games.service
Wants=distrobox-container@trantbox-dev.service distrobox-container@trantbox-services.service
Wants=distrobox-container@trantbox-utils.service
Wants=pipewire.service pipewire-pulse.service wireplumber.service
