[trantbox-desktop]
home=$HOME/.local/share/distrobox/home/trantbox-desktop
image=ghcr.io/ublue-os/bazzite-arch:latest
entry=true
nvidia=true
start_now=true

# dependencies
additional_packages=libnotify wl-clipboard
# desktop
additional_packages=firefox helvum obs-studio nvidia-settings btop gimp shotcut discord
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm webcord-bin brave-bin tor-browser-bin teams
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm pwvucontrol hyprsysteminfo bottles
exported_apps=firefox helvum obs nvidia-settings btop gimp shotcut discord
exported_apps=webcord brave tor-browser teams pwvucontrol hyprsysteminfo bottles # games
additional_packages=steam umu-launcher
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm legacy-launcher
exported_apps=steam legacy-launcher
; volume=/extra/$USER/.local/share/Steam:$HOME/.local/share/distrobox/home/trantbox-desktop/.local/share/Steam:rw
; volume=/extra/$USER/Games:$HOME/.local/share/distrobox/home/trantbox-desktop/Games:rw
; volume=/extra/$USER/Unity:$HOME/.local/share/distrobox/home/trantbox-desktop/Unity:rw
# dev
additional_packages=gcc make which git fzf nodejs npm neovim neovide tmux
additional_packages=python3 tree-sitter-cli dotnet-sdk luarocks
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm godot-beta-bin unityhub rider
exported_apps=neovide godot-beta unityhub rider
exported_bins=/usr/bin/nvim /usr/bin/tmux /usr/bin/fzf
volume=$HOME/.ssh:$HOME/.local/share/distrobox/home/trantbox-desktop/.ssh:rw
volume=$HOME/.config/git:$HOME/.local/share/distrobox/home/trantbox-desktop/.config/git:rw

init_hooks=touch /etc/init

[trantbox-services]
home=$HOME/.local/share/distrobox/home/trantbox-services
image=quay.io/toolbx/arch-toolbox:latest
entry=true
start_now=true

# general
additional_packages=profile-sync-daemon fcitx5 fcitx5-unikey fcitx5-configtool playerctl
init_hooks=cp /usr/share/psd/contrib/brave /usr/share/psd/browsers/brave
exported_apps=fcitx5-configtool
exported_bins=/usr/bin/fcitx5 /usr/bin/playerctld
# wayland
additional_packages=swaync waybar cliphist wl-clipboard
additional_packages=hyprpaper hyprsunset
exported_bins=/usr/bin/wl-copy /usr/bin/wl-paste /usr/bin/cliphist
# X11
additional_packages=picom feh
exported_bins=/usr/bin/picom /usr/bin/feh

volume=$HOME/.local/share/distrobox/home/trantbox-desktop/.mozilla:$HOME/.local/share/distrobox/home/trantbox-services/.mozilla:rw
volume=$HOME/.local/share/distrobox/home/trantbox-desktop/.config/BraveSoftware:$HOME/.local/share/distrobox/home/trantbox-services/.config/BraveSoftware:rw

[trantbox-utils]
home=$HOME/.local/share/distrobox/home/trantbox-utils
image=quay.io/toolbx/arch-toolbox:latest
entry=true
start_now=true

# essential
additional_packages=ripgrep fd stow fastfetch zoxide brightnessctl catimg unzip bat libnotify
exported_bins=/usr/bin/rg /usr/bin/fd /usr/bin/stow /usr/bin/fastfetch /usr/bin/zoxide
exported_bins=/usr/bin/catimg /usr/bin/unzip /usr/bin/notify-send /usr/bin/wtype /usr/bin/bat
# wayland
additional_packages=wtype
# hyprland
additional_packages=hyprshot hyprpicker
exported_bins=/usr/bin/hyprshot /usr/bin/hyprpicker
