unbind=SUPER, L
unbind=SUPER, H
unbind=SUPER, K
unbind=SUPER, J
unbind=SUPER SHIFT, L
unbind=SUPER SHIFT, H
unbind=SUPER SHIFT, K
unbind=SUPER SHIFT, J

unbind=SUPER CTRL, L
unbind=SUPER CTRL, H
unbind=SUPER CTRL, K
unbind=SUPER CTRL, J

# unbind=SUPER SHIFT, 1
# unbind=SUPER SHIFT, 2
# unbind=SUPER SHIFT, 3
# unbind=SUPER SHIFT, 4
# unbind=SUPER SHIFT, 5
# unbind=SUPER SHIFT, 6
# unbind=SUPER SHIFT, 7
# unbind=SUPER SHIFT, 8
# unbind=SUPER SHIFT, 9
# unbind=SUPER SHIFT, 0
# unbind=SUPER SHIFT, N
# unbind=SUPER SHIFT, P
# unbind=SUPER SHIFT, bracketright
# unbind=SUPER SHIFT, bracketleft
#
# unbind=SUPER SHIFT, Tab

bind=SUPER, L, layoutmsg, focus r
bind=SUPER, H, layoutmsg, focus l
bind=SUPER, K, layoutmsg, focus u
bind=SUPER, J, layoutmsg, focus d
bind=SUPER SHIFT, L, layoutmsg, movewindowto r
bind=SUPER SHIFT, H, layoutmsg, movewindowto l
bind=SUPER SHIFT, K, layoutmsg, movewindowto u
bind=SUPER SHIFT, J, layoutmsg, movewindowto d

binde=SUPER CTRL, L, layoutmsg, colresize +conf
binde=SUPER CTRL, H, layoutmsg, colresize -conf

bind=SUPER ALT, F, layoutmsg, togglefit
bind=SUPER ALT, L, layoutmsg, swapcol r
bind=SUPER ALT, H, layoutmsg, swapcol l

# bind=SUPER SHIFT, 1, layoutmsg, movecoltoworkspace 1
# bind=SUPER SHIFT, 2, layoutmsg, movecoltoworkspace 2
# bind=SUPER SHIFT, 3, layoutmsg, movecoltoworkspace 3
# bind=SUPER SHIFT, 4, layoutmsg, movecoltoworkspace 4
# bind=SUPER SHIFT, 5, layoutmsg, movecoltoworkspace 5
# bind=SUPER SHIFT, 6, layoutmsg, movecoltoworkspace 6
# bind=SUPER SHIFT, 7, layoutmsg, movecoltoworkspace 7
# bind=SUPER SHIFT, 8, layoutmsg, movecoltoworkspace 8
# bind=SUPER SHIFT, 9, layoutmsg, movecoltoworkspace 9
# bind=SUPER SHIFT, 0, layoutmsg, movecoltoworkspace 10
# bind=SUPER SHIFT, N, layoutmsg, movecoltoworkspace e+1
# bind=SUPER SHIFT, P, layoutmsg, movecoltoworkspace e-1
# bind=SUPER SHIFT, bracketright, layoutmsg, movecoltoworkspace +1
# bind=SUPER SHIFT, bracketleft, layoutmsg, movecoltoworkspace -1
#
# bind=SUPER SHIFT, Tab, layoutmsg, movecoltoworkspace previous
