scrolling {
    column_width=0.9
    explicit_column_widths=0.4, 0.6, 0.9, 1.0
    fullscreen_on_one_column=true
}

unbind=SUPER, L
unbind=SUPER, H
unbind=SUPER, K
unbind=SUPER, J

unbind=SUPER ALT, F
unbind=SUPER ALT, L
unbind=SUPER ALT, H

bind=SUPER, L, layoutmsg, focus r
bind=SUPER, H, layoutmsg, focus l
bind=SUPER, K, layoutmsg, focus u
bind=SUPER, J, layoutmsg, focus d

bind=SUPER ALT, F, layoutmsg, togglefit
bind=SUPER ALT, L, layoutmsg, swapcol r
bind=SUPER ALT, H, layoutmsg, swapcol l

binde=SUPER CTRL, L, layoutmsg, colresize +conf
binde=SUPER CTRL, H, layoutmsg, colresize -conf
