# plugin: xtra-dispatcher
# hyprlang noerror true
bind=SUPER, D, plugin:xtd:throwunfocused, special:stash
bind=SUPER SHIFT, D, plugin:xtd:bringallfrom, special:stash
bind=SUPER SHIFT, C, plugin:xtd:closeunfocused,
# hyprlang noerror false
