[packages.archlinux]
pacman = [
    "base",
    "base-devel",
    "blueman",
    "booster",
    "btop",
    "chezmoi",
    "cmake",
    "cosign",
    "dconf-editor",
    "dysk",
    "fastfetch",
    "firefox",
    "fish",
    "flatpak",
    "ghostty",
    "git",
    "go",
    "gopass",
    "hyprland",
    "hyprpolkitagent",
    "intel-ucode",
    "kitty",
    "less",
    "linux",
    "linux-firmware",
    "linux-headers",
    "man-db",
    "ncdu",
    "networkmanager",
    "noto-fonts",
    "noto-fonts-cjk",
    "noto-fonts-emoji",
    "noto-fonts-extra",
    "openssh",
    "pipewire-pulse",
    "podlet",
    "podman",
    "podman-compose",
    "quickshell",
    "reflector",
    "rofi",
    "sbctl",
    "smartmontools",
    "ttf-firacode-nerd",
    "uwsm",
    "vim",
    "vulkan-intel",
    "vulkan-tools",
    "wev",
    "wl-clipboard",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "zram-generator",
]
aur = ["chezetc", "dashbinsh", "ttf-ms-fonts"]
