general {
  after_sleep_cmd=tutils idle --after_resume
  before_sleep_cmd=tutils idle --before_sleep
  lock_cmd=tutils --lock
}

listener {
  on-resume=tutils idle --resume 1
  on-timeout=tutils idle --timeout 1
  timeout=150
}

listener {
  on-timeout=tutils idle --timeout 2
  timeout=300
}

listener {
  on-resume=tutils idle --resume 3
  on-timeout=tutils idle --timeout 3
  timeout=330
}

listener {
  on-timeout=tutils idle --timeout 4
  timeout=1800
}
