[Unit]
Wants=hyprpolkitagent.service fumon.service
Wants=trantbox-services-swayidle.service trantbox-services-waybar.service trantbox-services-awww.service trantbox-services-wlsunset.service
Wants=trantbox-services-swaync.service trantbox-services-cliphist.service
