[trantbox-desktop]
home=$DISTROBOX_HOME/trantbox-desktop
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
nvidia=true
start_now=true
# dependencies
additional_packages=libnotify wl-clipboard qt5-wayland
# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist.old ] || mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist ] || cp /run/host/etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist || cp /etc/pacman.d/mirrorlist.old /etc/pacman.d/mirrorlist
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-desktop/.config/fish:ro
volume=trantbox-desktop-cache:/var/cache/pacman/pkg:rw
# main
additional_packages=firefox thunderbird hyprpwcenter obs-studio nvidia-settings btop gimp shotcut discord libreoffice-fresh drawio-desktop
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm webcord-bin brave-bin tor-browser-bin teams
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm pwvucontrol bottles sfxr-qt-bin --overwrite=/usr/lib/libgstcuda-1.0.so\*
exported_apps=firefox thunderbird hyprpwcenter obs nvidia-settings btop gimp shotcut discord libreoffice drawio
exported_apps=webcord brave tor-browser teams pwvucontrol bottles sfxr
volume=$DOTFILES_DIR/stow/WebCord/dot-config/WebCord/Themes:$DISTROBOX_HOME/trantbox-desktop/.config/WebCord/Themes:ro
volume=$DOTFILES_DIR/stow/btop/dot-config/btop:$DISTROBOX_HOME/trantbox-desktop/.config/btop:ro
# final
init_hooks=touch /etc/init
init_hooks=rm -f /usr/bin/xdg-open

[trantbox-games]
home=$DISTROBOX_HOME/trantbox-games
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
nvidia=true
start_now=true
unshare_netns=true
# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist.old ] || mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist ] || cp /run/host/etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist || cp /etc/pacman.d/mirrorlist.old /etc/pacman.d/mirrorlist
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-games/.config/fish:ro
volume=trantbox-games-cache:/var/cache/pacman/pkg:rw
# force discrete gpu
additional_flags=--env-file $DOTFILES_DIR/misc/distrobox/nvidia.env
# essential
additional_packages=openal pipewire pipewire-pulse pipewire-alsa pipewire-jack wireplumber mangohud
# main
additional_packages=steam umu-launcher
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm legacy-launcher
exported_apps=steam legacy-launcher
volume=$DOTFILES_DIR/trantbox/trantbox-games/dot-local/share/Steam/steam_dev.cfg:$DISTROBOX_HOME/trantbox-games/.local/share/Steam/steam_dev.cfg:ro
volume=$DOTFILES_DIR/trantbox/trantbox-games/dot-config/Mangohud:$DISTROBOX_HOME/trantbox-games/.config/Mangohud:ro
# final
init_hooks=touch /etc/init
init_hooks=rm -f /usr/bin/xdg-open

[trantbox-dev]
home=$DISTROBOX_HOME/trantbox-dev
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
nvidia=true
start_now=true
# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist.old ] || mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist ] || cp /run/host/etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist || cp /etc/pacman.d/mirrorlist.old /etc/pacman.d/mirrorlist
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-dev/.config/fish:ro
volume=trantbox-dev-cache:/var/cache/pacman/pkg:rw
# force discrete gpu
additional_flags=--env-file $DOTFILES_DIR/misc/distrobox/nvidia.env
# essential
additional_packages=wl-clipboard ripgrep gcc make which git nodejs npm go
additional_packages=python3 tree-sitter-cli dotnet-sdk luarocks
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/stow
# general
additional_packages=zellij
init_hooks=[ -f /etc/init ] || pacman -S --needed --noconfirm neovide --assume-installed neovim
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm neovim-nightly-bin
exported_apps=neovide
exported_bins=/usr/bin/nvim /usr/bin/zellij
volume=$DOTFILES_DIR/stow/neovide/dot-config/neovide:$DISTROBOX_HOME/trantbox-dev/.config/neovide:ro
volume=$DOTFILES_DIR/stow/neovim/dot-config/nvim:$DISTROBOX_HOME/trantbox-dev/.config/nvim:ro
volume=$DOTFILES_DIR/stow/zellij/dot-config/zellij:$DISTROBOX_HOME/trantbox-dev/.config/zellij:ro
volume=$DOTFILES_DIR/trantbox/trantbox-dev/dot-config/nvim/lazy-lock.json:$DISTROBOX_HOME/trantbox-dev/.config/nvim/lazy-lock.json:rw
volume=$HOME/.ssh:$DISTROBOX_HOME/trantbox-dev/.ssh:ro
volume=$HOME/.config/git:$DISTROBOX_HOME/trantbox-dev/.config/git:ro
# gamedev
additional_packages=godot
init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm unityhub rider
exported_apps=godot unityhub rider
volume=$DOTFILES_DIR/trantbox/trantbox-dev/dot-local/share/unity3d/.gitkeep:$DISTROBOX_HOME/trantbox-dev/.local/share/unity3d/.gitkeep
# final
init_hooks=touch /etc/init
init_hooks=rm -f /usr/bin/xdg-open

[trantbox-services]
home=$DISTROBOX_HOME/trantbox-services
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
start_now=true
# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist.old ] || mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist ] || cp /run/host/etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist || cp /etc/pacman.d/mirrorlist.old /etc/pacman.d/mirrorlist
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-services/.config/fish:ro
volume=trantbox-services-cache:/var/cache/pacman/pkg:rw
# general
additional_packages=fcitx5 fcitx5-unikey fcitx5-configtool mpv
exported_apps=fcitx5-configtool mpv
exported_bins=/usr/bin/fcitx5
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-local/share/fcitx5/themes:$DISTROBOX_HOME/trantbox-services/.local/share/fcitx5/themes:ro
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/fcitx5:$DISTROBOX_HOME/trantbox-services/.config/fcitx5:rw
# wayland
additional_packages=swaync cliphist wl-clipboard
exported_bins=/usr/bin/wl-copy /usr/bin/wl-paste /usr/bin/cliphist /usr/bin/swaync-client
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/swaync:$DISTROBOX_HOME/trantbox-services/.config/swaync:ro
# hyprland
additional_packages=hyprpaper hyprsunset
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/hypr:$DISTROBOX_HOME/trantbox-services/.config/hypr:ro
# X11
additional_packages=picom feh
exported_bins=/usr/bin/picom /usr/bin/feh
volume=$DOTFILES_DIR/trantbox/trantbox-services/dot-config/picom:$DISTROBOX_HOME/trantbox-services/.config/picom:ro
# final
init_hooks=touch /etc/init
init_hooks=rm -f /usr/bin/xdg-open

[trantbox-utils]
home=$DISTROBOX_HOME/trantbox-utils
image=ghcr.io/ublue-os/arch-toolbox:latest
entry=true
start_now=true
# host integration
pre_init_hooks=export SHELL=/usr/bin/fish
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist.old ] || mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
pre_init_hooks=[ -f /etc/pacman.d/mirrorlist ] || cp /run/host/etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist || cp /etc/pacman.d/mirrorlist.old /etc/pacman.d/mirrorlist
volume=$DOTFILES_DIR/trant/dot-config/fish:$DISTROBOX_HOME/trantbox-utils/.config/fish:ro
volume=trantbox-utils-cache:/var/cache/pacman/pkg:rw
# essential
additional_packages=rofimoji ripgrep fd fastfetch zoxide catimg unzip bat libnotify unrar trash-cli
exported_bins=/usr/bin/rofimoji /usr/bin/rg /usr/bin/fd /usr/bin/fastfetch /usr/bin/zoxide
exported_bins=/usr/bin/catimg /usr/bin/unzip /usr/bin/notify-send /usr/bin/unrar /usr/bin/bat
exported_bins=/usr/bin/trash-empty /usr/bin/trash-list /usr/bin/trash-put /usr/bin/trash-restore /usr/bin/trash-rm
volume=$DOTFILES_DIR/trantbox/trantbox-utils/dot-config/fastfetch:$DISTROBOX_HOME/trantbox-utils/.config/fastfetch:ro
volume=$DOTFILES_DIR/trantbox/trantbox-utils/dot-config/rofimoji.rc:$DISTROBOX_HOME/trantbox-utils/.config/rofimoji.rc:ro
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/rofi
# wayland
additional_packages=wtype
exported_bins=/usr/bin/wtype
# final
init_hooks=touch /etc/init
init_hooks=rm -f /usr/bin/xdg-open
