local set = vim.keymap.set

local textobjs_move = require("nvim-treesitter-textobjects.move")
local textobjs_repeat = require("nvim-treesitter-textobjects.repeatable_move")
local textobjs_select = require("nvim-treesitter-textobjects.select")
local textobjs_swap = require("nvim-treesitter-textobjects.swap")

set({ "x", "o" }, "aa", function()
	textobjs_select.select_textobject("@parameter.outer")
end)
set({ "x", "o" }, "ia", function()
	textobjs_select.select_textobject("@parameter.inner")
end)
set({ "x", "o" }, "af", function()
	textobjs_select.select_textobject("@function.outer")
end)
set({ "x", "o" }, "if", function()
	textobjs_select.select_textobject("@function.inner")
end)
set({ "x", "o" }, "ac", function()
	textobjs_select.select_textobject("@class.outer")
end)
set({ "x", "o" }, "ic", function()
	textobjs_select.select_textobject("@class.inner")
end)

set("n", "<leader>sl", function()
	textobjs_swap.swap_next("@parameter.inner")
end)
set("n", "<leader>sh", function()
	textobjs_swap.swap_previous("@parameter.inner")
end)

set({ "n", "x", "o" }, "]a", function()
	textobjs_move.goto_next("@parameter.outer")
end)
set({ "n", "x", "o" }, "[a", function()
	textobjs_move.goto_previous("@parameter.outer")
end)
set({ "n", "x", "o" }, "]f", function()
	textobjs_move.goto_next("@function.outer")
end)
set({ "n", "x", "o" }, "[f", function()
	textobjs_move.goto_previous("@function.outer")
end)
set({ "n", "x", "o" }, "]c", function()
	textobjs_move.goto_next("@class.outer")
end)
set({ "n", "x", "o" }, "[c", function()
	textobjs_move.goto_previous("@class.outer")
end)

set({ "n", "x", "o" }, ";", textobjs_repeat.repeat_last_move_next)
set({ "n", "x", "o" }, ",", textobjs_repeat.repeat_last_move_previous)
set({ "n", "x", "o" }, "f", textobjs_repeat.builtin_f_expr, { expr = true })
set({ "n", "x", "o" }, "F", textobjs_repeat.builtin_F_expr, { expr = true })
set({ "n", "x", "o" }, "t", textobjs_repeat.builtin_t_expr, { expr = true })
set({ "n", "x", "o" }, "T", textobjs_repeat.builtin_T_expr, { expr = true })
