[Unit]
Wants=hypridle.service hyprpolkitagent.service fumon.service
Wants=trantbox-services-hyprpaper.service trantbox-services-hyprsunset.service
Wants=trantbox-services-swaync.service trantbox-services-waybar.service
Wants=trantbox-services-cliphist.service
