[Unit]
Wants=hypridle.service hyprpolkitagent.service fumon.service
Wants=podman-container@trantbox-desktop.service podman-container@trantbox-games.service
Wants=podman-container@trantbox-dev.service
Wants=trantbox-services-hyprpaper.service trantbox-services-hyprsunset.service
Wants=trantbox-services-swaync.service trantbox-services-waybar.service
Wants=trantbox-services-cliphist.service
