general {
  after_sleep_cmd=t_controller idle after_resume
  before_sleep_cmd=t_controller idle before_sleep
  lock_cmd=t_controller lock
}

listener {
  on-resume=t_controller idle resume 1
  on-timeout=t_controller idle timeout 1
  timeout=150
}

listener {
  on-timeout=t_controller idle timeout 2
  timeout=300
}

listener {
  on-resume=t_controller idle resume 3
  on-timeout=t_controller idle timeout 3
  timeout=330
}

listener {
  on-timeout=t_controller idle timeout 4
  timeout=1800
}
