$HYPRPAPER_BG=$DISTROBOX_HOST_HOME/Pictures/wallpapers/Snow-valley.jpg
$HYPRPAPER_BG_FALLBACK=/run/host/usr/share/hypr/wall2.png

ipc = off
preload = $HYPRPAPER_BG_FALLBACK
wallpaper = ,$HYPRPAPER_BG_FALLBACK
preload = $HYPRPAPER_BG
wallpaper = ,$HYPRPAPER_BG
